import { NextPage } from "next";
import Head from "next/head";
import { useAuth } from "src/context/auth";

const Home: NextPage = () => {
  const { user, signInWithGoogle, signOut } = useAuth();

  return (
    <div>
      <Head>
        <title>Hasura tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-2xl text-red-500">Welcome Next.js!</h1>
        <button className="py-2 px-5 mr-3 text-white bg-red-400 rounded-md" onClick={signInWithGoogle}>
          Sign in with Google
        </button>
        <button className="py-2 px-5 text-white bg-gray-500 rounded-md" onClick={signOut}>
          Sign out
        </button>
      </div>
    </div>
  );
};

export default Home;
